version: "3.8"

services:
  mariadb-server:
    image: mariadb:latest
    container_name: io-mariadb-server-container
    environment:
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: io-phpmyadmin-container
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: io-mariadb-server-container
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password123
    ports:
      - "8234:80"
    depends_on:
      - mariadb-server

  liquibase:
    image: liquibase/liquibase
    container_name: io-liquibase-container
    volumes:
      - ./liquibase:/liquibase
    depends_on:
      - mariadb-server
    command:
      - "--defaultsFile=/liquibase/liquibase.properties"
      - "update"
